// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIaGYJmm8_Suvf84tZ4VYKkdbmOglv2No',
    appId: '1:181190843418:web:a9f766a3e49d52cc1785a3',
    messagingSenderId: '181190843418',
    projectId: 'kafka-423811',
    authDomain: 'kafka-423811.firebaseapp.com',
    storageBucket: 'kafka-423811.appspot.com',
    measurementId: 'G-TSB8E411DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPZsmGU7YNMNfd2sqBDn81CKege8Wpp4A',
    appId: '1:181190843418:android:e1d220729c1e84fb1785a3',
    messagingSenderId: '181190843418',
    projectId: 'kafka-423811',
    storageBucket: 'kafka-423811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyUew2loazjdNxnCZXOL7bbq7z-nDAmL8',
    appId: '1:181190843418:ios:c64b37a3d89897511785a3',
    messagingSenderId: '181190843418',
    projectId: 'kafka-423811',
    storageBucket: 'kafka-423811.appspot.com',
    iosBundleId: 'com.example.pccwPost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyUew2loazjdNxnCZXOL7bbq7z-nDAmL8',
    appId: '1:181190843418:ios:0ef96e2f7e5bce551785a3',
    messagingSenderId: '181190843418',
    projectId: 'kafka-423811',
    storageBucket: 'kafka-423811.appspot.com',
    iosBundleId: 'com.example.maioPhotos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIaGYJmm8_Suvf84tZ4VYKkdbmOglv2No',
    appId: '1:181190843418:web:a6b1b2940877849c1785a3',
    messagingSenderId: '181190843418',
    projectId: 'kafka-423811',
    authDomain: 'kafka-423811.firebaseapp.com',
    storageBucket: 'kafka-423811.appspot.com',
    measurementId: 'G-3HNZ2MY0M6',
  );
}
