name: Generated APK

on:
  push:
    branches: [ 
      "test/ionex_homework", 
      "release/ionex_homework",
      "test/github_api", 
      "release/github_api",
    ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  PROJECT_NAME: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if github.base_ref is in array
        id: build
        run: |
          array=("ionex_homework" "github_api")
          IN="${{ env.BRANCH_NAME }}"
          IFS='/' read -ra paths <<< "$IN"
          for path in "${paths[@]}"
          do
            echo "path, $path"
            for item in "${array[@]}"; do
              echo "item, $item"
              if [[ "$path" == "$item" ]]; then
                echo "::set-env name=PROJECT_NAME::$item"
                break 2
              fi
            done
          done
          
      - name: Project name
        run: |
          echo "Project name is: $project_name"
      

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
    
      - name: Build APK
        run: cd ${{ env.PROJECT_NAME }} && ./gradlew assembleRelease