# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build app

on:
  push:
    branches: [ "test", "release" ]

jobs:
  affected-apps:
    runs-on: ubuntu-latest
    name: Try to choose a flutter app
    strategy:
      matrix:
        project_name: [curriculum, currency_conversion, maio_photos, playsee_story, ]
    outputs:
        app: ${{ steps.step1.outputs.app}}
    steps:
      - uses: actions/checkout@v3
      - id: step1
        run: |
          if startsWith(github.head_ref, '${{ matrix.project_name }}/') ; then
            echo 'app=${{ matrix.project_name }}' >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: affected-apps
    if: needs.affected-apps.outputs.app != ''
    runs-on: ubuntu-latest
    steps:
      - name: Check if project matches
        if: startsWith(github.head_ref, ${{ needs.affected-apps.outputs.app }}/)
        run: echo "Project name ${{ needs.affected-apps.outputs.app }}"

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - name: Install dependencies
        run: cd ${{ needs.affected-apps.outputs.app }} && flutter pub get

      - name: Generate files
        run: cd ${{ needs.affected-apps.outputs.app }} && flutter pub run build_runner build --delete-conflicting-outputs

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: cd ${{ needs.affected-apps.outputs.app }} && flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: cd ${{ needs.affected-apps.outputs.app }} && flutter test
      
      # Build Android Bundle release file
      - name: Build aab
        run: |
          cd ${{ matrix.project_name }} && flutter build apk
